sudo: required
services: 
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-205368330264"
  build_path: "docker-react"
  on:
    branch: master

access_key_id: 
  secure: "AKIAS7UHIBAMCMI6M2ZG"
secret_access_key:
  secure: "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"